num_dimensions: 32
use_neural_force: True
use_blackbox : False
num_simulations: 1000
train_iterations: 64
train_dt: 0.01
train_damping: 0.05
learning_rate: 0.003
init_pos_range: 1.0
enable_partitioning: False
number_of_subgraphs: 4
gradient_multisteps: 1
threshold: 1.0