model:
  hidden_channels : 24

dataset:
  id : 'bscl'
  train_size : 0.8
  root : 'src/data'

  transform: 
    largest_cc : True
    line_graph : True
    pe_type : 'laplacian'
    pe_size : 10

  simulation:
    n_simulations : 20
    n_nodes : 100
    p_positive : 0.5

    BSCL:
      dataset_id : 'bscl'
      sampling_method : 'exp'
      p_close_triangle : 0.1
      p_close_for_balance : 0.8
      remove_self_loops : True
      node_mask : False

  bitcoin:
    dataset_id : 'bitcoin'
    node_mask : True