model:
  n_layers : 5

dataset:
  id : 'bitcoin'
  train_size : 0.8
  pe_size : 20
  root : 'src/data'

  simulation:
    n_simulations : 100
    n_nodes : 100
    p_positive : 0.5

    BSCL:
      dataset_id : 'bscl'
      sampling_method : 'exp'
      p_close_triangle : 0.1
      p_close_for_balance : 0.8
      remove_self_loops : True
      node_mask : False

  bitcoin:
    dataset_id : 'bitcoin'
    node_mask : True