model:
  n_layers : 5
  hidden_mlp_dims : {'X': 256, 'E': 128, 'y': 128}
  hidden_dims : {'dx': 256, 'de': 64, 'dy': 64, 'n_head': 8, 'dim_ffX': 256, 'dim_ffE': 128, 'dim_ffy': 128}

dataset:
  n_graphs : 100
  n_nodes : 100

  BSCL:
    sampling_method : 'exp'
    p_positive : 0.9
    p_close_triangle : 0.1
    p_close_for_balance : 0.8
    remove_self_loops : True

