model:
  hidden_channels : 24
  balance_loss : True

  embedding:
    embedding_dim : 64
    walk_length : 10
    context_size : 5
    walks_per_node : 5
    epochs : 10

dataset:
  id : 'wiki'
  train_size : 0.8
  root : 'src/data'

  transform: 
    largest_cc : False
    line_graph : True
    pe_type : 'none'
    pe_size : 4

  simulation:
    n_simulations : 20
    n_nodes : 100
    p_positive : 0.5

    BSCL:
      dataset_id : 'bscl'
      sampling_method : 'exp'
      p_close_triangle : 0.1
      p_close_for_balance : 0.8
      remove_self_loops : True
      node_mask : False

  wiki:
    dataset_id : 'wiki'
    node_mask : True