model:
<<<<<<< HEAD
  hidden_channels : 2
  balance_loss : True
  epochs : 50

  spring_pe:
    embedding_dim : 4
    step_size : 0.02
    stiffness : 1.0
    iterations : 1000
    damping : 0.02
    friend_distance : 0.1
    enemy_distance : 10.0
    noise : 0.003
    

dataset:
  id : 'tribes'
=======
  hidden_channels : 24
  balance_loss : True

  embedding:
    embedding_dim : 64
    walk_length : 10
    context_size : 5
    walks_per_node : 5
    epochs : 10

dataset:
  id : 'wiki'
>>>>>>> 575938ec92c353b1620effe935986de8c2808464
  train_size : 0.8
  root : 'src/data'

  transform: 
    largest_cc : False
<<<<<<< HEAD
    line_graph : False
=======
    line_graph : True
    pe_type : 'none'
    pe_size : 4
>>>>>>> 575938ec92c353b1620effe935986de8c2808464

  simulation:
    n_simulations : 20
    n_nodes : 100
    p_positive : 0.5

    BSCL:
      dataset_id : 'bscl'
      sampling_method : 'exp'
      p_close_triangle : 0.1
      p_close_for_balance : 0.8
      remove_self_loops : True
      node_mask : False

  wiki:
    dataset_id : 'wiki'
<<<<<<< HEAD

  tribes:
    dataset_id : 'tribes'
=======
    node_mask : True
>>>>>>> 575938ec92c353b1620effe935986de8c2808464
