# SpringE
embedding_dim : 64
time_step : 0.003
iterations : 300
damping : 0.01
friend_distance : 2.0
friend_stiffness : 1.0
neutral_distance : 2.0
neutral_stiffness : 0.1
enemy_distance : 10.0
enemy_stiffness : 6.0

# dataset
id : 'bitcoin'
root : 'src/data'
test_size : 0.2