model:
  n_layers : 5

dataset:
  n_graphs : 200
  n_nodes : 100

  BSCL:
    sampling_method : 'exp'
    p_positive : 0.9
    p_close_triangle : 0.1
    p_close_for_balance : 0.8
    remove_self_loops : True

