model:
  n_layers : 5

dataset:
  n_graphs : 40
  n_nodes : 60
  laplacian_eigenvector_pe_size : 10

  BSCL:
    sampling_method : 'exp'
    p_positive : 0.9
    p_close_triangle : 0.1
    p_close_for_balance : 0.8
    remove_self_loops : True

